# Generated by Django 5.2.8 on 2025-12-04 14:41

import db.CustomUserManager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_alter_movie_title_user_order_ticket"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", db.CustomUserManager.CustomUserManager()),
            ],
        ),
    ]
